"""create initial database schema

Revision ID: 3bd7baf040a8
Revises:
Create Date: 2026-08-30 15:32:21.555567

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bd7baf040a8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_settings",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default="1",
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("required_channel_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("required_channel_username", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="ck_bot_settings_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_groups_telegram_chat_id", "groups", ["telegram_chat_id"], unique=True
    )
    op.create_index("ix_groups_username", "groups", ["username"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "scope",
            sa.Enum("DAILY", "GROUP", name="question_scope"),
            server_default="DAILY",
            nullable=False,
        ),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ANSWERED", "EXPIRED", name="question_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_questions_expires_at", "questions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_questions_published_at", "questions", ["published_at"], unique=False
    )
    op.create_index(
        "ix_questions_scope_status", "questions", ["scope", "status"], unique=False
    )
    op.create_table(
        "teachers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("damage", sa.Integer(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("purchase_price", sa.BigInteger(), nullable=False),
        sa.Column("upgrade_price", sa.BigInteger(), nullable=False),
        sa.Column("unlock_level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("ability_text", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("damage >= 0", name="ck_teachers_damage_non_negative"),
        sa.CheckConstraint("max_hp >= 0", name="ck_teachers_max_hp_non_negative"),
        sa.CheckConstraint(
            "purchase_price >= 0", name="ck_teachers_purchase_price_non_negative"
        ),
        sa.CheckConstraint(
            "unlock_level >= 1", name="ck_teachers_unlock_level_positive"
        ),
        sa.CheckConstraint(
            "upgrade_price >= 0", name="ck_teachers_upgrade_price_non_negative"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_teachers_name", "teachers", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("level >= 1", name="ck_users_level_positive"),
        sa.CheckConstraint(
            "referrer_id IS NULL OR referrer_id <> id",
            name="ck_users_cannot_refer_self",
        ),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_referrer_id", "users", ["referrer_id"], unique=False)
    op.create_index(
        "ix_users_telegram_user_id", "users", ["telegram_user_id"], unique=True
    )
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_table(
        "answers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("answer_content", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_answers_group_id", "answers", ["group_id"], unique=False)
    op.create_index("ix_answers_question_id", "answers", ["question_id"], unique=False)
    op.create_index("ix_answers_user_id", "answers", ["user_id"], unique=False)
    op.create_index(
        "uq_valid_group_question_answer",
        "answers",
        ["question_id", "group_id"],
        unique=True,
        postgresql_where=sa.text("group_id IS NOT NULL AND is_valid = true"),
    )
    op.create_table(
        "castles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("strength", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("level >= 1", name="ck_castles_level_positive"),
        sa.CheckConstraint("strength >= 0", name="ck_castles_strength_non_negative"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_castles_user_id", "castles", ["user_id"], unique=True)
    op.create_table(
        "resources",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("coin", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("diamond", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("banana", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("banana >= 0", name="ck_resources_banana_non_negative"),
        sa.CheckConstraint("coin >= 0", name="ck_resources_coin_non_negative"),
        sa.CheckConstraint("diamond >= 0", name="ck_resources_diamond_non_negative"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_resources_user_id", "resources", ["user_id"], unique=True)
    op.create_table(
        "rewards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum("COIN", "DIAMOND", "BANANA", name="resource_type"),
            nullable=False,
        ),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("reference_type", sa.String(length=64), nullable=True),
        sa.Column("reference_id", sa.BigInteger(), nullable=True),
        sa.Column("activity_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name="ck_rewards_amount_non_negative"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rewards_created_at", "rewards", ["created_at"], unique=False)
    op.create_index("ix_rewards_user_id", "rewards", ["user_id"], unique=False)
    op.create_index(
        "uq_daily_login_reward_per_user_date",
        "rewards",
        ["user_id", "activity_date"],
        unique=True,
        postgresql_where=sa.text(
            "source = 'DAILY_LOGIN' AND activity_date IS NOT NULL"
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum("COIN", "DIAMOND", "BANANA", name="resource_type"),
            nullable=False,
        ),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("balance_before", sa.BigInteger(), nullable=True),
        sa.Column("balance_after", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("reference_type", sa.String(length=64), nullable=True),
        sa.Column("reference_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance_after IS NULL OR balance_after >= 0",
            name="ck_transactions_after_non_negative",
        ),
        sa.CheckConstraint(
            "balance_before IS NULL OR balance_before >= 0",
            name="ck_transactions_before_non_negative",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transactions_created_at", "transactions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_transactions_user_created_at",
        "transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_id", "transactions", ["user_id"], unique=False
    )
    op.create_table(
        "user_teachers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("teacher_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("current_hp", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INJURED", "DISABLED", "RECOVERING", name="teacher_status"
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_hp >= 0", name="ck_user_teachers_current_hp_non_negative"
        ),
        sa.CheckConstraint("level >= 1", name="ck_user_teachers_level_positive"),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_teachers_teacher_id", "user_teachers", ["teacher_id"], unique=False
    )
    op.create_index(
        "ix_user_teachers_user_id", "user_teachers", ["user_id"], unique=False
    )
    op.create_index(
        "uq_user_teachers_user_teacher",
        "user_teachers",
        ["user_id", "teacher_id"],
        unique=True,
    )
    op.create_table(
        "attacks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("attacker_id", sa.BigInteger(), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column("teacher_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RESOLVED", name="attack_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolve_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("teacher_damage_snapshot", sa.Integer(), nullable=False),
        sa.Column("target_castle_strength_snapshot", sa.BigInteger(), nullable=False),
        sa.Column("target_defense_power_snapshot", sa.BigInteger(), nullable=False),
        sa.Column("result_damage", sa.BigInteger(), nullable=True),
        sa.Column("loot_coin", sa.BigInteger(), nullable=True),
        sa.Column("loot_diamond", sa.BigInteger(), nullable=True),
        sa.Column("loot_banana", sa.BigInteger(), nullable=True),
        sa.Column("is_successful", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "loot_banana >= 0", name="ck_attacks_loot_banana_non_negative"
        ),
        sa.CheckConstraint("loot_coin >= 0", name="ck_attacks_loot_coin_non_negative"),
        sa.CheckConstraint(
            "loot_diamond >= 0", name="ck_attacks_loot_diamond_non_negative"
        ),
        sa.CheckConstraint(
            "result_damage >= 0", name="ck_attacks_result_damage_non_negative"
        ),
        sa.CheckConstraint(
            "target_castle_strength_snapshot >= 0",
            name="ck_attacks_castle_strength_non_negative",
        ),
        sa.CheckConstraint(
            "target_defense_power_snapshot >= 0",
            name="ck_attacks_defense_power_non_negative",
        ),
        sa.CheckConstraint(
            "teacher_damage_snapshot >= 0",
            name="ck_attacks_teacher_damage_non_negative",
        ),
        sa.CheckConstraint(
            "attacker_id <> target_id", name="ck_attacks_different_users"
        ),
        sa.ForeignKeyConstraint(["attacker_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["user_teachers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_attacks_attacker_id", "attacks", ["attacker_id"], unique=False)
    op.create_index("ix_attacks_resolve_at", "attacks", ["resolve_at"], unique=False)
    op.create_index("ix_attacks_status", "attacks", ["status"], unique=False)
    op.create_index("ix_attacks_target_id", "attacks", ["target_id"], unique=False)
    op.create_index("ix_attacks_teacher_id", "attacks", ["teacher_id"], unique=False)
    op.create_index(
        "uq_pending_attack_per_teacher",
        "attacks",
        ["attacker_id", "target_id", "teacher_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "defenses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("castle_id", sa.BigInteger(), nullable=False),
        sa.Column("defense_power", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("defense_power >= 0", name="ck_defenses_power_non_negative"),
        sa.ForeignKeyConstraint(["castle_id"], ["castles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_defenses_castle_id", "defenses", ["castle_id"], unique=True)
    op.create_table(
        "recoveries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_teacher_id", sa.BigInteger(), nullable=False),
        sa.Column("recovery_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recovery_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "recovery_end_at > recovery_started_at",
            name="ck_recoveries_end_after_start",
        ),
        sa.ForeignKeyConstraint(
            ["user_teacher_id"], ["user_teachers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recoveries_recovery_end_at", "recoveries", ["recovery_end_at"], unique=False
    )
    op.create_index(
        "ix_recoveries_user_teacher_id", "recoveries", ["user_teacher_id"], unique=False
    )
    op.create_index(
        "uq_active_recovery_per_teacher",
        "recoveries",
        ["user_teacher_id"],
        unique=True,
        postgresql_where=sa.text("completed_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_recovery_per_teacher",
        table_name="recoveries",
        postgresql_where=sa.text("completed_at IS NULL"),
    )
    op.drop_index("ix_recoveries_user_teacher_id", table_name="recoveries")
    op.drop_index("ix_recoveries_recovery_end_at", table_name="recoveries")
    op.drop_table("recoveries")
    op.drop_index("ix_defenses_castle_id", table_name="defenses")
    op.drop_table("defenses")
    op.drop_index(
        "uq_pending_attack_per_teacher",
        table_name="attacks",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_attacks_teacher_id", table_name="attacks")
    op.drop_index("ix_attacks_target_id", table_name="attacks")
    op.drop_index("ix_attacks_status", table_name="attacks")
    op.drop_index("ix_attacks_resolve_at", table_name="attacks")
    op.drop_index("ix_attacks_attacker_id", table_name="attacks")
    op.drop_table("attacks")
    op.drop_index("ix_user_teachers_user_id", table_name="user_teachers")
    op.drop_index("ix_user_teachers_teacher_id", table_name="user_teachers")
    op.drop_index("uq_user_teachers_user_teacher", table_name="user_teachers")
    op.drop_table("user_teachers")
    op.drop_index("ix_transactions_user_id", table_name="transactions")
    op.drop_index("ix_transactions_user_created_at", table_name="transactions")
    op.drop_index("ix_transactions_created_at", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(
        "uq_daily_login_reward_per_user_date",
        table_name="rewards",
        postgresql_where=sa.text(
            "source = 'DAILY_LOGIN' AND activity_date IS NOT NULL"
        ),
    )
    op.drop_index("ix_rewards_user_id", table_name="rewards")
    op.drop_index("ix_rewards_created_at", table_name="rewards")
    op.drop_table("rewards")
    op.drop_index("ix_resources_user_id", table_name="resources")
    op.drop_table("resources")
    op.drop_index("ix_castles_user_id", table_name="castles")
    op.drop_table("castles")
    op.drop_index(
        "uq_valid_group_question_answer",
        table_name="answers",
        postgresql_where=sa.text("group_id IS NOT NULL AND is_valid = true"),
    )
    op.drop_index("ix_answers_user_id", table_name="answers")
    op.drop_index("ix_answers_question_id", table_name="answers")
    op.drop_index("ix_answers_group_id", table_name="answers")
    op.drop_table("answers")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_index("ix_users_telegram_user_id", table_name="users")
    op.drop_index("ix_users_referrer_id", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_teachers_name", table_name="teachers")
    op.drop_table("teachers")
    op.drop_index("ix_questions_scope_status", table_name="questions")
    op.drop_index("ix_questions_published_at", table_name="questions")
    op.drop_index("ix_questions_expires_at", table_name="questions")
    op.drop_table("questions")
    op.drop_index("ix_groups_username", table_name="groups")
    op.drop_index("ix_groups_telegram_chat_id", table_name="groups")
    op.drop_table("groups")
    op.drop_table("bot_settings")
    op.execute("DROP TYPE IF EXISTS attack_status")
    op.execute("DROP TYPE IF EXISTS teacher_status")
    op.execute("DROP TYPE IF EXISTS resource_type")
    op.execute("DROP TYPE IF EXISTS question_status")
    op.execute("DROP TYPE IF EXISTS question_scope")
    # ### end Alembic commands ###
